src.training.claim_detection:
  train_set_json_path: data/task_2.1/train.json
  dev_set_json_path: data/task_2.1/dev.json
  tuned_model_name: bert-base-uncased
  n_epochs: 16
  batch_size: 4
  lr: 5e-6
  plots_save_path: plots/claim_detection/

src.training.argument_relation_detection:
  train_set_json_path: data/task_2.2/train.json
  dev_set_json_path: data/task_2.2/dev.json
  tuned_model_name: bert-base-uncased
  n_epochs: 16
  batch_size: 4
  lr: 5e-6
  plots_save_path: plots/argument_relation_detection/