src.training.claim_detection:
  train_set_json_path: data/task_2.1/train.json
  dev_set_json_path: data/task_2.1/train.json
  tuned_model_name: bert-base-uncased
  n_epochs: 8
  batch_size: 4
  lr: 1e-4